version: "3.3"
services:
  proxy:
            build: .
            container_name: proxy
            ports:
            - "80:80"
            restart: always

networks:
    default:
       external:
           name: rede_containers


