apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2  
        resources:
          limits:
            memory: "256Mi"
            cpu: 0.7
          requests:
            memory: "128Mi"
            cpu: 0.4           
        ports:
        - containerPort: 80
